### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Adriianh** [Maxuss/Macrocosm#12]
I'll list the errors/bugs I have found so far.

**ERRORS**
- PlayerInteractEvent: https://pastes.dev/HvKvJKMbtn
  This error occurs when you try to interact with any item, whether added by Macrocosm or not. Examples:
  1) When killing a monster
  2) By right clicking
  3) When clicking on a block

- PlayerCalculateStatEvent: https://pastes.dev/slfE68eUFJ
  Occurs when you equip an item or armor that increases your stats.

- Resourcepack generation: https://pastes.dev/0n4nKxBlmn
  The resourcepack is not generated correctly at server startup, it's not applied to players when they enter the server.

**BUGS**
- Items Menu (/items)
  When the next page button is pressed, the page changes four times and it should be only once.

**Comment by Maxuss** [comment]
Fixed in #13
